# Generated by Django 4.1.13 on 2026-01-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_mentor_user_is_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML')], default='python', max_length=20),
        ),
        migrations.AlterField(
            model_name='module',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('code', 'Code Challenge')], max_length=10),
        ),
    ]
