# Generated by Django 4.1.13 on 2026-01-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_module_language_alter_module_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='quiz_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
