# Generated by Django 4.1.13 on 2026-01-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_module_quiz_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='For mentor payouts', max_length=50),
        ),
    ]
