# Generated by Django 4.1.13 on 2026-01-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_bank_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('penulis', 'Penulis'), ('pembaca', 'Pembaca')], default='pembaca', max_length=20),
        ),
    ]
