# Generated by Django 6.0.1 on 2026-01-23 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('penulis', 'Penulis')], max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(blank=True, help_text='Leave blank for global rate', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
            options={
                'db_table': 'commission_rates',
                'unique_together': {('role', 'course')},
            },
        ),
    ]
