# Generated by Django 6.0.1 on 2026-01-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_commissionrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='percentage',
        ),
        migrations.AddField(
            model_name='commission',
            name='rate_type',
            field=models.CharField(choices=[('percentage', 'Percentage (%)'), ('flat', 'Flat (Rp)')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='commission',
            name='rate_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage or Flat amount', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commissionrate',
            name='flat_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Used if type is flat', max_digits=12),
        ),
        migrations.AddField(
            model_name='commissionrate',
            name='rate_type',
            field=models.CharField(choices=[('percentage', 'Percentage (%)'), ('flat', 'Flat (Rp)')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='commission',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='commissionrate',
            name='percentage',
            field=models.DecimalField(decimal_places=2, help_text='Used if type is percentage', max_digits=12),
        ),
        migrations.AlterField(
            model_name='commissionrate',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('penulis', 'Penulis'), ('layanan', 'Layanan')], max_length=20),
        ),
    ]
