# Generated by Django 6.0.1 on 2026-01-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_commission_percentage_commission_rate_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='rate_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage or Flat amount', max_digits=12),
        ),
    ]
