# Generated by Django 6.0.1 on 2026-01-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_commission_rate_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('penulis', 'Penulis'), ('layanan', 'Layanan')], default='penulis', max_length=20),
        ),
    ]
