# Generated by Django 6.0.1 on 2026-01-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_commission_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionrate',
            name='flat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Used if type is flat', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commissionrate',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Used if type is percentage', max_digits=12, null=True),
        ),
    ]
