# Generated by Django 6.0.1 on 2026-01-28 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_commissionrate_flat_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='questions',
        ),
        migrations.AddField(
            model_name='assessment',
            name='questions_json',
            field=models.JSONField(blank=True, db_column='questions', null=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='assessments/questions/')),
                ('order', models.IntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.assessment')),
            ],
            options={
                'db_table': 'assessment_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assessments/choices/')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.question')),
            ],
            options={
                'db_table': 'assessment_choices',
            },
        ),
    ]
